### ISSUE TITLE
Can't reproduce results due to dependency API change

### ISSUE THREAD

**Issue by avi-jain** [jvendrow/GuidedNMF#1]
Hey,

I tried to run the News notebook. It seems like the ssnmf version you've used is [0.0.2](https://pypi.org/project/ssnmf/0.0.2/) and the current one's 1.0.3. It's got some breaking changes. Could you maybe update the code?
I can help with a PR if you can direct me towards the changes required. You can also perhaps add a requirements.txt to fix your dependencies

Thanks!

**Comment by jvendrow** [comment]
Hi. Sorry for the delay. To run the notebook you can install an older version of the ssnmf package using 
`pip install ssnmf==0.0.2`.
To address this I added a `requirements.txt` file.
